# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2")do|config|
  config.vm.box="base.box"

  ## Les 3 lignes suivantes permettent d'éviter certains bugs et/ou d'accélérer le déploiement. Gardez-les tout le temps sauf contre-indications.
  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false
  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false 
  
  # Creates a Hsot-only network access to the machine
  # using a specific IP
  config.vm.network "private_network", ip: "192.168.1.30"
  
  # Provider-specific configuration to fine-tune the VM:
  config.vm.provider "virtualbox" do |vb|
    # displays the VB gui when booting the machine:
    vb.gui = false
    # customises the amount of memory
    vb.memory = "2048"
    # define Name (for Vagrant) and Hostname:
    config.vm.hostname = "node0"
    vb.name = "MC_Server"
    vb.cpus = 2
    # Crée le disque, uniquement s'il nexiste pas déjà
  end
  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
    config.vm.synced_folder ".", "/vagrant", disabled: true

end

